default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USER") { "admin" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "123" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: 3306

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "locacao_midias" } %>

test:
  <<: *default
  database: locacao_midias_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "locacao_midias" } %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>